# Generated by Django 2.0.8 on 2018-09-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180930_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='images',
            new_name='image',
        ),
    ]
