# Generated by Django 2.0.8 on 2018-10-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_interest'),
        ('notifications', '0007_auto_20181014_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Category'),
        ),
    ]
