# Generated by Django 2.0.8 on 2018-09-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180930_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='smk950226@naver.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
