# Generated by Django 2.0.8 on 2018-10-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
            ],
        ),
    ]
